apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: node-port-scanner
  name: node-port-scanner
  namespace: sre
spec:
  selector:
    matchLabels:
      app: node-port-scanner
  template:
    metadata:
      labels:
        app: node-port-scanner
    spec:
      hostNetwork: true
      containers:
      - image: ismaelfm/node-port-scanner:latest
        name: node-port-scanner
        resources:
          limits:
            cpu: "10m"
            memory: "100Mi"
        requests:
            cpu: "1m"
            memory: "50Mi"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        envFrom:
        - configMapRef: 
            name: node-port-scanner
        - secretRef:
            name: node-port-scanner
        resources: {}
