apiVersion: v1
kind: Service
metadata:
  name: node-port-scanner
  namespace: sre
  labels:
    app: node-port-scanner
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:    
    app: node-port-scanner