name: "Continuous Integrations"

on:
  push:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-central-1

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    outputs:
     image: ${{ steps.pusher.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building and pushing image
        run: |
          make release
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          